### ISSUE TITLE
Baking of Animations in Blender

### ISSUE THREAD

**Issue by francescoandreussi** [FilmakademieRnd/TracerSceneDistribution#8]
As a character animator I want to be able to bake animations represented as TRACER AnimationParameters into Blender actions (keyframes) so it can be refined in a further step with Blender functionality.

Acceptance criteria:
- [x] Write animation on the timeline when receiving a ParameterUpdate containing a list of keys
- [x] Test performance when receiving regular and many updates

**Comment by FaisalZ** [comment]
UI refinement:

- [x] Received animation from AnimHost is overwriting timeline (everytime an AnimationParameter with Keyframes is received)
- [x] Additional button to bake control rig and FK data into timeline animation and create an NLA strip
